#ifndef JIT_api_h
#define JIT_api_h

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

	/**
	* The Jit Context defines a container for the Jit machinery and
	* also acts as the repository of the compiled functions. The Jit
	* Context must be kept alive as long as any functions within it are
	* needed. Deleting the Jit Context will also delete all compiled
	* functions managed by the context.
	*/
	typedef struct JIT_context *JIT_contextref;

	/**
	* Creates a Jit Context. 
	*/
	extern JIT_contextref JIT_create_context();

	/**
	* Destroys the Jit Context. Note that all compiled functions
	* managed by this context will die at this point.
	*/
	extern void JIT_destroy_context(JIT_contextref);

	/**
	* A Function Builder is used to generate code for a single
	* C function equivalent. Once the code is generated by invoking
	* finalize on the builder, the builder itself can be destroyed as the
	* compiled function lives on in the associated Jit Context.
	*/
	typedef struct JIT_function_builder *JIT_function_builderref;

	/*
	* These types are used to define function argument
	* types. See JIT_create_function_builder() below for further
	* notes.
	*/
	enum JIT_value_kind {
		JIT_valuekind_V = 0, // void 
		JIT_valuekind_I = 1, // int32_t
		JIT_valuekind_Q = 2, // uint64_t
		JIT_valuekind_D = 3, // double
		JIT_valuekind_F = 4, // single-precision float;
		JIT_valuekind_P = 5, // pointer
	};

	/**
	* Creates a new function builder object. The builder is used to construct the
	* code that will go into one function. Once the function has been defined,
	* machine code is generated by calling finalize(). After the function is
	* compiled the builder object can be thrown away - the compiled function
	* will live as long as the owning Jit Context lives.
	*/
	extern JIT_function_builderref JIT_create_function_builder(
		JIT_contextref context, const char *name, enum JIT_value_kind return_type);

	/**
	* Destroys the function builder object. Note that this will not delete the
	* compiled function created using this builder - as the compiled function lives
	* in the owning Jit Context.
	*/
	extern void JIT_destroy_function_builder(JIT_function_builderref);

	/**
	* A value type
	*/
	typedef struct JIT_value *JIT_valueref;

	extern JIT_valueref JIT_imm32(JIT_function_builderref fb, int32_t i);

	extern void JIT_ret(JIT_function_builderref fb, JIT_valueref v);

	extern void *JIT_finalize(JIT_function_builderref fb);

#ifdef __cplusplus
}
#endif


#endif